### ISSUE TITLE
implement atnOf for AllStar dependency

### ISSUE THREAD

**Issue by cronburg** [cronburg/antlr-haskell#1]
On branch allstar in the file `src/Text/ANTLR/Allstar.hs`. There's a reference implementation already in `src/Text/ANTLR/Allstar/ATN.hs`, but our representations of an ATN are substantially different that we'll probably just need to reimplement it. Do you want to do this @slasser? We can talk in person.

**Comment by slasser** [comment]
I've updated my ATN representation so that it's much more similar to yours--let's see if that resolves the compatibility issue.

**Comment by cronburg** [comment]
ef4e80e1d7963d380a0dde6da46fa4bbb5afb874 closes this - kept the same `atnOf` function and wrote a conversion from the antlr ATN type to the AllStar repo's ATN type.
