### ISSUE TITLE
Build failure with GHC 8.0.2, AllStar d7abbd5, set-monad 0.2.0.0

### ISSUE THREAD

**Issue by ony** [cronburg/antlr-haskell#28]
Thank you for working on an interesting project. I was looking for some parser for ANTLR files and found this.
Right now I'm trying to bring this as a package to Linux distro I'm using for development and it failed to build for me. Can you help to resolve this issue?

```
src/Text/ANTLR/Allstar/Stacks.hs:24:17: error:
    * No instance for (Ord (Set [a]))
        arising from the first field of `Stacks' (type `Set [a]')
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    * When deriving the instance for (Ord (Stacks a))
[18 of 28] Compiling Paths_antlr_haskell ( dist/build/autogen/Paths_antlr_haskell.hs, dist/build/Paths_antlr_haskell.o )
```

[Referenced code](https://github.com/cronburg/antlr-haskell/blob/f973c018eaa7ff3e104638f0316e3c9c08a9bd90/src/Text/ANTLR/Allstar/Stacks.hs#L20-L24):
```haskell
data Stacks a =
    Empty
  | Wildcard
  | Stacks (Set [a])
deriving (Eq, Ord, Generic, Hashable, Show)
```
Unfortunately looking at it I also can't imagine how would look instance for `Ord (Set anything)`. Thus I have no idea how to fix it.

Thank you.

More info on dependencies:

```
Configuring antlr-haskell-0.1.0.0...
Dependency AllStar -any: using AllStar-0.1.0.0
Dependency HUnit -any: using HUnit-1.2.5.2
Dependency QuickCheck -any: using QuickCheck-2.8.2
Dependency antlr-haskell -any: using antlr-haskell-0.1.0.0
Dependency base >=4.7: using base-4.9.1.0
Dependency call-stack -any: using call-stack-0.1.0
Dependency containers -any: using containers-0.5.7.1
Dependency deepseq -any: using deepseq-1.4.2.0
Dependency hashable -any: using hashable-1.2.4.0
Dependency haskell-src-meta -any: using haskell-src-meta-0.6.0.14
Dependency mtl -any: using mtl-2.2.1
Dependency parsec -any: using parsec-3.1.9
Dependency set-monad -any: using set-monad-0.2.0.0
Dependency template-haskell -any: using template-haskell-2.11.1.0
Dependency test-framework -any: using test-framework-0.8.1.1
Dependency test-framework-hunit -any: using test-framework-hunit-0.3.0
Dependency test-framework-quickcheck2 -any: using
test-framework-quickcheck2-0.3.0.3
Dependency text -any: using text-1.2.2.0
Dependency th-lift -any: using th-lift-0.7.6
Dependency transformers -any: using transformers-0.5.2.0
Dependency unordered-containers -any: using unordered-containers-0.2.7.1
Using Cabal-1.24.2.0 compiled by ghc-8.0
Using compiler: ghc-8.0.2
```

Full log can be found [here](https://paste.pound-python.org/raw/BIb71eKZhzeEfGJIuHra/)

**Comment by cronburg** [comment]
You could try importing Data.HashSet directly and changing the `Stacks (Set [a])` line to `Stacks (HashSet [a])`. The Ord instance already exists, it's just that the older version of GHC can't seem to figure that out. I ran into this build failure before, but I'm running at least GHC 8.2 nowadays.

**Comment by ony** [comment]
That's unexpected to have `Ord` for collection without intuitive one winning ordering. I suspect, it was introduced solely to get `Set (HashSet a)` out of the box. Ehh... 

I've tried to use `HashSet` without type alias and apparently in `unordered-containers-0.2.7.1` there is no `Ord` instance for `HashSet` but in `unordered-containers-0.2.9.0` there is and it is still compatible with GHC 8.0.2 (`base (>=4.7 && <5)` matches `base-4.9.1.0`):
```
[17 of 28] Compiling Text.ANTLR.MultiMap ( src/Text/ANTLR/MultiMap.hs, dist/build/Text/ANTLR/MultiMap.o )

src/Text/ANTLR/MultiMap.hs:18:42: error:
    • No instance for (Ord (HashSet v))
        arising from the first field of ‘Map’ (type ‘M.Map k (HashSet v)’)
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Lift (Map k v))
[18 of 28] Compiling Text.ANTLR.Allstar.Stacks ( src/Text/ANTLR/Allstar/Stacks.hs, dist/build/Text/ANTLR/Allstar/Stacks.o )

src/Text/ANTLR/Allstar/Stacks.hs:25:17: error:
    • No instance for (Ord (HashSet [a]))
        arising from the first field of ‘Stacks’ (type ‘HashSet [a]’)
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Ord (Stacks a))
```

Thus it worth to put lower boundary on `unordered-containers`.

**Comment by cronburg** [comment]
Yeah, the Ord instance only matters insofar as there's some canonical ordering so that HashSets can be put in a binary tree or whatever other data structure Set was implemented with. At one point I considered doing something like `a < b = (sort . fromList) a < (sort . fromList) b` to define an ordering of sets.

**Comment by cronburg** [comment]
Does this build failure persist for you? A lot of the dependencies have been cleaned up in the meantime: namely AllStar and set-monad have been integrated directly into this project, and others most notably parsec have been eliminated.

You might also try pulling from Hackage now that this package is available there: https://hackage.haskell.org/package/antlr-haskell-0.1.0.0
