### ISSUE TITLE
Cabal file missing

### ISSUE THREAD

**Issue by jrp2014** [cronburg/antlr-haskell#44]
The README suggests that is should be possible to build this project with `cabal`, but there is no `.cabal` or `cabal.project` file.

**Comment by cronburg** [comment]
`hpack` should be able to generate a compliant cabal file. See the updated README. Unfortunately I don't intend to support generated files directly included in the repo, like is recommended in https://github.com/commercialhaskell/stack/issues/5210.

**Comment by jrp2014** [comment]
Thanks
